### ISSUE TITLE
Can we display color picker smaller, or as a popup?

### ISSUE THREAD

**Issue by cade-bryant-swbc** [innovixx/payload-color-picker-field#1]
I really like this color picker that you've written.  But my users feel that the component is too large.  They would like to see it either much smaller, or as a popup component that displays when they click or hover over a field.  Is this possible?

**Comment by kalon-robson** [comment]
Hi @cade-bryant-swbc Thank you for bringing this up. I think the component now looks a lot better.

If you have any further improvement suggestions, please let me know?
